CREATE TABLE [Subjects] (
[SubjectID] INT PRIMARY KEY IDENTITY,
[SubjectName] VARCHAR(30) NOT NULL
);

CREATE TABLE [Majors] (
[MajorID] INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(30) NOT NULL
);

CREATE TABLE [Students] (
[StudentID] INT PRIMARY KEY IDENTITY, 
[StudentNumber] VARCHAR(10) UNIQUE NOT NULL,
[StudentName] VARCHAR(30) NOT NULL,
[MajorID] INT FOREIGN KEY REFERENCES [Majors]([MajorID])
);

CREATE TABLE [Agenda] (
[StudentID] INT FOREIGN KEY REFERENCES [Students]([StudentID]),
[SubjectID] INT FOREIGN KEY REFERENCES [Subjects]([SubjectID]),
PRIMARY KEY ([StudentID], [SubjectID])
);

CREATE TABLE [Payments] (
[PaymentID] INT PRIMARY KEY IDENTITY,
[PaymentDate] DATETIME2 NOT NULL,
[PaymentAmount] DECIMAL (8, 2) NOT NULL,
[StudentID] INT REFERENCES [Students]([StudentID])
);